import type { Metadata } from "next";
import "./globals.css";
import { UserSettingsProvider } from "@/lib/contexts/UserSettingsContext";
import ThemeProvider from "./components/ThemeProvider";
import { Alfa_Slab_One, Caveat, Special_Elite } from "next/font/google";

const alfaSlabOne = Alfa_Slab_One({
  weight: "400",
  variable: "--font-heading",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-handwriting",
  subsets: ["latin"],
});

const specialElite = Special_Elite({
  weight: "400",
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${alfaSlabOne.variable} ${caveat.variable} ${specialElite.variable} antialiased`} suppressHydrationWarning>
        <ThemeProvider>
          <UserSettingsProvider>
            {children}
          </UserSettingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
